# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesapal_transaction', uuidfield.fields.UUIDField(max_length=32)),
                ('merchant_reference', models.CharField(db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('payment_method', models.CharField(max_length=24, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('merchant_reference', 'pesapal_transaction')]),
        ),
    ]
