# Generated by Django 3.2.25 on 2024-12-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pesapal', '0005_auto_20160503_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_reference',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.IntegerField(choices=[(999, 'Invalid'), (1, 'Completed'), (2, 'Failed'), (3, 'Reversed'), (999, 'Pending')], default=999),
        ),
    ]
