# Generated by Django 3.2.25 on 2024-12-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pesapal', '0006_auto_20241227_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_account',
            field=models.CharField(default='', max_length=64),
        ),
    ]
